apiVersion: apps/v1
kind: Deployment
metadata:
  name: std-jira
  namespace: prod-jira
  labels:
    app.kubernetes.io/name: std-jira
    app.kubernetes.io/env: prod
    app.kubernetes.io/project: STD.JIRA
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: std-jira
      app.kubernetes.io/env: prod
      app.kubernetes.io/project: STD.JIRA
      app.kubernetes.io/type: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: std-jira
        app.kubernetes.io/env: prod
        app.kubernetes.io/project: STD.JIRA
        app.kubernetes.io/type: app
    spec:
      serviceAccountName: std-jira

      containers:
        - name: jira
          image: atlassian/jira-software:10.0.0
          ports:
            - containerPort: 8080
          env:
            - name: CATALINA_OPTS
              value: "-javaagent:/mnt/agent/atlassian-agent.jar"

            # reverse proxy settings
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_TOMCAT_SECURE
              value: "false"
            - name: ATL_PROXY_NAME
              value: "jira.inso.gov.ir"
            - name: ATL_PROXY_PORT
              value: "443"

            # disable remote features
            - name: ATL_PLUGIN_MANAGER_DISABLE_REMOTE_PLUGIN_UPDATES
              value: "true"
            - name: UPM_ENABLE_MARKETPLACE
              value: "false"
            - name: UPM_DISABLE_RSS
              value: "true"
            - name: DISABLE_EXTERNAL_AVATARS
              value: "true"
            - name: ATL_TELEMETRY_ENABLED
              value: "false"
            - name: ATL_TUNNEL_SERVICE
              value: "disabled"
            - name: ATL_MAIL_DISABLED
              value: "true"
            - name: ATL_UPM_DISABLE_VERIFICATION
              value: "true"

            # JVM
            - name: JVM_MINIMUM_MEMORY
              value: "2048m"
            - name: JVM_MAXIMUM_MEMORY
              value: "2048m"

          volumeMounts:
            - name: jira-data
              mountPath: /var/atlassian/application-data/jira

          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"

      volumes:
        - name: jira-data
          persistentVolumeClaim:
            claimName: jira-pvc

