apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-agent-pvc
  namespace: prod-vsc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs