apiVersion: v1
kind: Service
metadata:
  name: std-jira
  namespace: prod-jira
  labels:
    app.kubernetes.io/name: std-jira
    app.kubernetes.io/env: prod
spec:
  selector:
    app.kubernetes.io/name: std-jira
    app.kubernetes.io/env: prod
  type: ClusterIP
  ports:
    - name:  http
      port: 80
      targetPort: 8080

